// <auto-generated />
namespace _31201024010_DoVoHuongThao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HoaDon1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HoaDon1));
        
        string IMigrationMetadata.Id
        {
            get { return "202303110140473_HoaDon1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
