// <auto-generated />
namespace _31201024010_DoVoHuongThao.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HoaDon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HoaDon));
        
        string IMigrationMetadata.Id
        {
            get { return "202303101506336_HoaDon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
